Do not ignore Prophecy
Dhii/services pull request #16
Opened 2022-12-20 15:27 UTC by XedinUnknown

Seems that this dependency is no longer getting installed, which is causing Psalm to complail.

2023-01-04 13:15 UTC, XedinUnknown commented
@mecha, @Biont, you wanna try this to confirm whether it breaks your stuff? Looks like the repo went out of date while Psalm inspections improved.

2023-01-05 11:47 UTC, mecha requested changes

2023-01-05 11:47 UTC, mecha commented on src/Factories/StringService.php
> +    protected function resolveString(string $serviceName, ContainerInterface $c): string
I don't like that this method is duplicated across 2 classes. Perhaps we should add a utility function somewhere that both of these classes can call.

2023-01-16 10:01 UTC, mecha commented on src/Factories/StringService.php
> +    protected function resolveString(string $serviceName, ContainerInterface $c): string
Looking at this again and - I'm not sure what I thought I saw - I don't see the other "occurrence" of this code. I must have made a mistake.

2023-01-16 10:05 UTC, mecha approved these changes
I've tested these changes on my local copy of #15 and can confirm that the changes do not add any undesired side-effects.

2023-01-24 15:45 UTC, Biont commented
@XedinUnknown @mecha It took me a while, but I was also able to confirm that there are no apparent side-effects/breakages introduced in this branch

2023-01-24 15:46 UTC, Biont approved these changes

2023-01-24 18:56 UTC, XedinUnknown commented
Thanks! I think we have all the assurance we need right now.

2023-01-27 11:29 UTC, merged